# --- Security ---------------------------------------------------------------
mp.jwt.verify.publickey.location=http://127.0.0.1:8180/realms/saas/protocol/openid-connect/certs
mp.jwt.verify.issuer=http://127.0.0.1:8180/realms/saas
mp.jwt.verify.audiences=saas-api

# --- Messaging --------------------------------------------------------------
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.order-created-in.connector=smallrye-kafka
mp.messaging.incoming.order-created-in.topic=order-created
mp.messaging.incoming.order-created-in.group.id=notification-service
mp.messaging.incoming.order-created-in.auto.offset.reset=earliest
mp.messaging.incoming.order-created-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.order-created-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# --- OpenAPI ----------------------------------------------------------------
mp.openapi.extensions.smallrye.info.title=Notification Service API
mp.openapi.extensions.smallrye.info.version=1.0.0
